# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a813a16b76cc289d6cea4b78f239ab212c10f8078540dbe056a9c1ddbbd72dbc32ee7712727340a0426f4bfee20cb197d9f9a9c57a6b248b55feed5c4e25abf

test:
  secret_key_base: 66b5e0977f3106ce8178a75ce620dd2049bfd3526caa1c542036be5af0ca3106987dd201c10cccfbad2a9fa7dc686f0d87679b0bef5fb091213ef33f0789045b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
